"""Reference system-layer building blocks for PQ satellite authentication.

This package is not a production cryptographic implementation.  The current
modules freeze canonical framing and exercise the one-time ticket state machine
without selecting a PQ AKE, holder authenticator, or durable distributed store.
"""

from .admission import (
    PUBLIC_ACCESS_PENDING,
    PUBLIC_ACCESS_REJECTION,
    AccessAdmissionOutcome,
    AccessPolicyVerifier,
    AccessSessionPreparationBackend,
    AdmissionDisposition,
    ChallengeCookieVerifier,
    HolderAuthenticationVerifier,
    OneTimeAccessAdmissionService,
    OneTimeAccessStore,
    PreparedAccessSession,
    SessionPreparationContext,
    UEKeyConfirmationVerifier,
    one_time_access_admission_manifest,
)
from .access import (
    REFERENCE_SUITE,
    REFERENCE_SUITE_ID,
    AccessAcceptV1,
    AccessChallengeV1,
    AccessFinishV1,
    AccessInitV1,
    ProtocolBindingError,
    ServingContextV1,
    SuiteLimits,
    access_accept_digest,
    access_challenge_digest,
    access_init_digest,
    access_transcript_digest,
    decode_access_accept,
    decode_access_challenge,
    decode_access_finish,
    decode_access_init,
    derive_attempt_id,
    encode_access_accept,
    encode_access_challenge,
    encode_access_finish,
    encode_access_finish_core,
    encode_access_init,
)
from .framing import (
    FrameType,
    FrameV1,
    ProtocolEncodingError,
    decode_frame,
    decode_opaque,
    encode_frame,
    encode_opaque,
)
from .identities import TicketUseIdentity, derive_use_key
from .replay import (
    Consumption,
    IdentityConflict,
    InMemoryLinearizableReplayStore,
    InvalidTransition,
    RevocationChanged,
    RevocationSnapshot,
    Reservation,
    ReservationNotFound,
    ReserveDisposition,
    ReserveResult,
    TicketUnavailable,
    TicketRevoked,
)

__all__ = [
    "AccessAdmissionOutcome",
    "AccessAcceptV1",
    "AccessChallengeV1",
    "AccessFinishV1",
    "AccessInitV1",
    "AccessPolicyVerifier",
    "AccessSessionPreparationBackend",
    "AdmissionDisposition",
    "ChallengeCookieVerifier",
    "Consumption",
    "FrameType",
    "FrameV1",
    "IdentityConflict",
    "InMemoryLinearizableReplayStore",
    "InvalidTransition",
    "HolderAuthenticationVerifier",
    "OneTimeAccessAdmissionService",
    "OneTimeAccessStore",
    "PUBLIC_ACCESS_PENDING",
    "PUBLIC_ACCESS_REJECTION",
    "PreparedAccessSession",
    "ProtocolBindingError",
    "ProtocolEncodingError",
    "REFERENCE_SUITE",
    "REFERENCE_SUITE_ID",
    "RevocationChanged",
    "RevocationSnapshot",
    "Reservation",
    "ReservationNotFound",
    "ReserveDisposition",
    "ReserveResult",
    "TicketUnavailable",
    "TicketRevoked",
    "ServingContextV1",
    "SessionPreparationContext",
    "SuiteLimits",
    "TicketUseIdentity",
    "UEKeyConfirmationVerifier",
    "access_accept_digest",
    "access_challenge_digest",
    "access_init_digest",
    "access_transcript_digest",
    "decode_access_accept",
    "decode_access_challenge",
    "decode_access_finish",
    "decode_access_init",
    "decode_frame",
    "decode_opaque",
    "derive_attempt_id",
    "derive_use_key",
    "encode_access_accept",
    "encode_access_challenge",
    "encode_access_finish",
    "encode_access_finish_core",
    "encode_access_init",
    "encode_frame",
    "encode_opaque",
    "one_time_access_admission_manifest",
]
